### ISSUE TITLE
Sign multiple certs from a single CA

### ISSUE THREAD

**Issue by kargakis** [Masterminds/sprig#147]
I need to setup a CA and sign certificates with it in Helm. I have the following named templates in `_helpers.tpl`:
```
{{/*
Generate CA
*/}}
{{- define "gen-ca" -}}
{{- genCA "cluster-ca" 365 -}}
{{- end -}}

{{- define "ca-crt" -}}
{{- $ca := (include "gen-ca" .) -}}
cluster-ca.crt: {{ $ca.Cert | b64enc }}
{{- end -}}

{{- define "ca-key" -}}
{{- $ca := (include "gen-ca" .) -}}
cluster-ca.key: {{ $ca.Key | b64enc }}
{{- end -}}

{{/*
Generate certificates for front
*/}}
{{- define "front.gen-certs" -}}
{{- $altNames := list ( printf "front.%s" .Release.Namespace ) ( printf "front.%s.svc" .Release.Namespace ) -}}
{{- $ca := (include "front.gen-ca" .) -}}
{{- $cert := genSignedCert "front" nil $altNames 365 $ca -}}
front.crt: {{ $cert.Cert | b64enc }}
front.key: {{ $cert.Key | b64enc }}
{{- end -}}

{{/*
Generate certificates for back
*/}}
{{- define "back.gen-certs" -}}
{{- $bkAltNames := list ( printf "back.%s" .Release.Namespace ) ( printf "back.%s.svc" .Release.Namespace ) -}}
{{- $ca := (include "gen-ca" .) -}}
{{- $cert := genSignedCert "back" nil $bkAltNames 365 $ca -}}
back.crt: {{ $cert.Cert | b64enc }}
back.key: {{ $cert.Key | b64enc }}
{{- end -}}
```
Then try to use those certificates in secrets, eg:
```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: front
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "front.gen-certs" . ) | indent 2 }}
```
When trying to create my helm template I get the following error:
```
Error: render error in "rt/templates/front.secret.yaml": template: rt/templates/front.secret.yaml:10:5: executing "rt/templates/front.secret.yaml" at <include "front.g...>: error calling include: template: rt/templates/_helpers.tpl:74:65: executing "front.gen-certs" at <$ca>: wrong type for value; expected sprig.certificate; got string
```
How can I get a certificate object in `front.gen-certs` and `back.gen-certs`? Is there a better way to do what I want to achieve? Sorry if this is the wrong place to ask.
