### ISSUE TITLE
Unable to access `genCA` attributes

### ISSUE THREAD

**Issue by chilledornaments** [Masterminds/sprig#267]
When using Helm 2 and Helm 3, I'm unable to access the `Cert` and `Key` attributes of `genCA`. Strangely, the map is populated and `genSignedCert` works as expected.

Helm versions:

```
helm version
Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

```
helm3 version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

**Example**

`_helpers.tpl`:

```go
{{- define "webhook.certs" -}}
{{- $fullName := ( include "auth-proxy-injector.fullname" . ) -}}
# fullname, fullname.namespace, fullname.namespace.svc
{{- $altNames := list ( printf "%s" $fullName ) ( printf "%s.%s" $fullName .Release.Namespace ) ( printf "%s.%s.svc" $fullName .Release.Namespace ) -}}
{{- $ca := genCA "auth-proxy-injector" 3650 -}}
{{- $cert := genSignedCert ( include "auth-proxy-injector.fullname" . ) nil $altNames 3650 $ca -}}
caCert: {{ $ca.Cert | b64enc }}
caCertMap: {{ $ca  }}
clientCert: {{ $cert.Cert | b64enc }}
clientKey: {{ $cert.Key | b64enc }}
{{- end -}}
```

`templates/webhook.yaml`:

```go
{{ $tls := fromYaml ( include "webhook.certs" . ) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "auth-proxy-injector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    caMap: {{ $tls.caCertMap }}
    app: {{ include "auth-proxy-injector.fullname" . }}
{{ include "auth-proxy-injector.labels" . | indent 4 }}
webhooks:
  - name: {{ include "auth-proxy-injector.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    clientConfig:
      caBundle: {{ if .Values.generateCerts }} {{ $tls.caCert }} {{ else }} {{ .Values.clusterCABundle }} {{ end }}
...
```

`tls_secret.yaml`:

```go
{{ $tls := fromYaml ( include "webhook.certs" . ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-proxy-injector.tlsname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "auth-proxy-injector.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ if .Values.generateCerts }} {{ $tls.clientCert }} {{ else }} {{ .Values.base64EncodedCertificate }} {{ end }}
  tls.key: {{ if .Values.generateCerts }} {{ $tls.clientKey }} {{ else }} {{ .Values.base64EncodedKey }} {{ end }}
```

`helm install --dry-run --debug ./ -n test` output (keys and certs truncated):

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: test-auth-proxy-injector
  namespace: default
  labels:
    caMap: map[-----BEGIN CERTIFICATE----- MIIDCD... -----END CERTIFICATE----- -----BEGIN RSA PRIVATE KEY----- MIIEpA... -----END RSA PRIVATE KEY-----:<nil>]
    app: test-auth-proxy-injector
    app.kubernetes.io/name: auth-proxy-injector
    helm.sh/chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/instance: test
    app: auth-proxy-injector
    chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Tiller
webhooks:
  - name: test-auth-proxy-injector.default.svc.cluster.local
    clientConfig:
      caBundle:
...

apiVersion: v1
kind: Secret
metadata:
  name: test-auth-proxy-injector-tls
  namespace: default
  labels:
    app.kubernetes.io/name: auth-proxy-injector
    helm.sh/chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/instance: test
    app: auth-proxy-injector
    chart: auth-proxy-injector-0.1.3
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Tiller
type: kubernetes.io/tls
data:
  tls.crt:  LS0tLS... 
  tls.key:  LS0tLS...
```

I expected `MutatingWebhookConfiguration.webhooks[0].clientConfig.caBundle` to not be empty. I'm seeing this issue on Minikube and on EKS clusters (Kubernetes 1.16)

**Comment by mitchya1** [comment]
I've played around with this some more and discovered that if I move the `genCA` and `genSignedCert` calls, along with the kube secret, to the `webhook.yaml` file, everything works as expected.

`webhook.yaml`:

```go
{{ $fullName := ( include "auth-proxy-injector.fullname" . ) }}
# fullname, fullname.namespace, fullname.namespace.svc
{{- $altNames := list ( printf "%s" $fullName ) ( printf "%s.%s" $fullName .Release.Namespace ) ( printf "%s.%s.svc" $fullName .Release.Namespace ) -}}
{{- $ca := genCA "auth-proxy-injector" 3650 -}}
{{- $cert := genSignedCert ( include "auth-proxy-injector.fullname" . ) nil $altNames 3650 $ca -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "auth-proxy-injector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "auth-proxy-injector.fullname" . }}
{{ include "auth-proxy-injector.labels" . | indent 4 }}
webhooks:
  - name: {{ include "auth-proxy-injector.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    clientConfig:
      caBundle: {{ if .Values.generateCerts }} {{ $ca.Cert | b64enc }} {{- else -}} {{ .Values.clusterCABundle }} {{ end }}
...
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-proxy-injector.tlsname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "auth-proxy-injector.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ if .Values.generateCerts }} {{ $cert.Cert | b64enc }} {{ else }} {{ .Values.base64EncodedCertificate }} {{ end }}
  tls.key: {{ if .Values.generateCerts }} {{ $cert.Key | b64enc }} {{ else }} {{ .Values.base64EncodedKey }} {{ end }}
```

Output:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: brown-worm-auth-proxy-injector-tls
  namespace: default
  labels:
    app.kubernetes.io/name: auth-proxy-injector
    helm.sh/chart: auth-proxy-injector-0.1.4
    app.kubernetes.io/instance: brown-worm
    app: auth-proxy-injector
    chart: auth-proxy-injector-0.1.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Tiller
type: kubernetes.io/tls
data:
  tls.crt:  LS0tLS1CRUdJTiBD...
  tls.key:  LS0tLS1CRUdJTiBS..
...
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: brown-worm-auth-proxy-injector
  namespace: default
  labels:
    app: brown-worm-auth-proxy-injector
    app.kubernetes.io/name: auth-proxy-injector
    helm.sh/chart: auth-proxy-injector-0.1.4
    app.kubernetes.io/instance: brown-worm
    app: auth-proxy-injector
    chart: auth-proxy-injector-0.1.4
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Tiller
webhooks:
  - name: brown-worm-auth-proxy-injector.default.svc.cluster.local
    clientConfig:
      caBundle:  LS0tLS1CRUdJTiBDR...
...
```
