### ISSUE TITLE
Feature Request: flatten function

### ISSUE THREAD

**Issue by rmetzler** [Masterminds/sprig#312]
In my Helm charts, I would like to reuse lists. The main issue is the syntax for this and while it' simple to do so for YAML hashes, it's not as simple for lists. So I came up with the notation of writing something like:

```yaml
list1: &list1
- a
- b
- c

list2:
- *list1
- 1
- 2
- 3
```

This creates a nested list `list2` and the `flatten` function should turn it into a flat list which looks like:

```yaml
list2:
- a
- b
- c
- 1
- 2
- 3
```
