### ISSUE TITLE
can indent work on multi-line template definition?

### ISSUE THREAD

**Issue by JeanMertz** [Masterminds/sprig#57]
Given:

```yaml
{{- define "foobar" }}
foo:
  bar: baz
{{- end }}

qux:
{{- template "foobar" . | indent 2 }}
```

I'd like to get:

```yaml
qux:
  foo:
    bar: baz
```

Given the above, I get:

```
executing "test" at <2>: wrong type for value; expected string; got map[string]interface {}
```

Using `{{- template "foobar" . | toString | indent 2 }}` I get:

```
qux:
foo:
  bar: baz
```

Meaning the line(s) never get indented. Even doing `{{ template "foobar" . | join "_" | indent 2 }}` results in the above, so clearly piping after `template` isn't working as I hoped it would.

Are there any ways to solve this?
